version: '2'
services:
  pro_team_resource_planner-app:
    image: pro_team_resource_planner
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://pro_team_resource_planner-mysql:3306/pro_team_resource_planner?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://pro_team_resource_planner-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://pro_team_resource_planner-elasticsearch:9200
    ports:
      - 8080:8080
  pro_team_resource_planner-mysql:
    extends:
      file: mysql.yml
      service: pro_team_resource_planner-mysql
  pro_team_resource_planner-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: pro_team_resource_planner-elasticsearch
